Client:
    type: entity
    table: client
    fields:
        idclient:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: idClient
            generator:
                strategy: IDENTITY
        login:
            type: string
            length: 50
            fixed: false
            nullable: false
        username:
            type: string
            length: 255
            fixed: false
            nullable: false
        pwd:
            type: string
            length: 25
            fixed: false
            nullable: false
        nom:
            type: string
            length: 50
            fixed: false
            nullable: false
        prenom:
            type: string
            length: 50
            fixed: false
            nullable: false
        email:
            type: string
            length: 50
            fixed: false
            nullable: false
        telephone:
            type: integer
            unsigned: false
            nullable: false
        adresse:
            type: string
            length: 100
            fixed: false
            nullable: false
        cin:
            type: integer
            unsigned: false
            nullable: false
        actif:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
