Commentaire:
    type: entity
    table: commentaire
    fields:
        idcommentaire:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: idCommentaire
            generator:
                strategy: IDENTITY
        contenu:
            type: string
            length: 500
            fixed: false
            nullable: false
        date:
            type: datetime
            nullable: false
    manyToOne:
        idclient:
            targetEntity: Client
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idClient:
                    referencedColumnName: idClient
            orphanRemoval: false
        idoffre:
            targetEntity: Offre
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idOffre:
                    referencedColumnName: idOffre
            orphanRemoval: false
    lifecycleCallbacks: {  }
