Offre:
    type: entity
    table: offre
    fields:
        idoffre:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: idOffre
            generator:
                strategy: IDENTITY
        sujetoffre:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: sujetOffre
        contenu:
            type: string
            length: 500
            fixed: false
            nullable: false
        date:
            type: datetime
            nullable: false
    manyToOne:
        idagence:
            targetEntity: Agence
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idAgence:
                    referencedColumnName: idAgence
            orphanRemoval: false
    lifecycleCallbacks: {  }
