Reclamation:
    type: entity
    table: reclamation
    fields:
        idreclamation:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: idReclamation
            generator:
                strategy: IDENTITY
        sujetreclamation:
            type: string
            length: 25
            fixed: false
            nullable: false
            column: sujetReclamation
        contenu:
            type: string
            length: 500
            fixed: false
            nullable: false
        etat:
            type: boolean
            nullable: false
        date:
            type: datetime
            nullable: false
    manyToOne:
        idclient:
            targetEntity: Client
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idClient:
                    referencedColumnName: idClient
            orphanRemoval: false
        idagence:
            targetEntity: Agence
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idAgence:
                    referencedColumnName: idAgence
            orphanRemoval: false
    lifecycleCallbacks: {  }
