<?php

namespace Proxies\__CG__\Esprit\TaxiDriverBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Agence extends \Esprit\TaxiDriverBundle\Entity\Agence implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setIdagence($idagence)
    {
        $this->__load();
        return parent::setIdagence($idagence);
    }

    public function getIdagence()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idagence"];
        }
        $this->__load();
        return parent::getIdagence();
    }

    public function setNomagence($nomagence)
    {
        $this->__load();
        return parent::setNomagence($nomagence);
    }

    public function getNomagence()
    {
        $this->__load();
        return parent::getNomagence();
    }

    public function setTelagence($telagence)
    {
        $this->__load();
        return parent::setTelagence($telagence);
    }

    public function getTelagence()
    {
        $this->__load();
        return parent::getTelagence();
    }

    public function setAdresseagence($adresseagence)
    {
        $this->__load();
        return parent::setAdresseagence($adresseagence);
    }

    public function getAdresseagence()
    {
        $this->__load();
        return parent::getAdresseagence();
    }

    public function setIdrespagence(\Esprit\TaxiDriverBundle\Entity\Responsableagence $idrespagence = NULL)
    {
        $this->__load();
        return parent::setIdrespagence($idrespagence);
    }

    public function getIdrespagence()
    {
        $this->__load();
        return parent::getIdrespagence();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idagence', 'nomagence', 'telagence', 'adresseagence', 'idrespagence');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}