parameters:
#    esprit_taxi_driver.example.class: Esprit\TaxiDriverBundle\Example

services:
#    esprit_taxi_driver.example:
#        class: %esprit_taxi_driver.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
